repos:
  # Standard Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  # CI/CD Hooks
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-github-actions
        args: ["--verbose"]
      - id: check-dependabot
        args: ["--verbose"]

  # Spellchecker Hooks
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--write-changes"]
