name: "Pre Commit"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pre-commit-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Pre Commit
        uses: mystic-framework/github-actions/pre-commit@v1
